// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raxwiltikdoytmydiqth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJheHdpbHRpa2RveXRteWRpcXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTYzMTEsImV4cCI6MjA2NTU3MjMxMX0.q_DfPapstj1De59IlIE0e3s41JgonojQx1oe2Doytr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);